### ISSUE TITLE
ja.jsonの共同編集化

### ISSUE THREAD

**Issue by lispcoc** [YASUYASUYASUYASU/common#1]
例のリポジトリの管理人です。↓の件のご連絡どうもです。
https://jbbs.shitaraba.net/bbs/read.cgi/game/9358/1534596627/371

大変申し訳ないのですが、[こちら](https://github.com/lispcoc/Cataclysm-DDA-JPMODS)のリポジトリはGitHubに馴染みのない人がスレの大部分を占める現状では、機能させることが難しいと考え現在凍結中です。

ただ、ja.jsonに色んな人が考えた名前を追加していくというのは面白いアイデアだし、是非協力したいなと思ってます。
まずはGoogle Spreadシート等でGitHubの知識がなくても共同編集ができる環境を立ち上げて、それを自分がjsonに変換して定期的にGitHubに上げて管理していく……みたいな感じで。

いずれにせよいったん専用のリポジトリを新しく立ち上げる形でやらせてもらいたいなーと思ってますが、いかがでしょうか。

**Comment by YASUYASUYASUYASU** [comment]
そうですね・・・仰る通りです。GitHubの知識がなくても
共同編集ができる環境が今は望ましいですね、
>>いずれにせよいったん専用のリポジトリを新しく立ち上げる形でやらせてもらいたいなーと
>>思ってますが、いかがでしょうか
⇒はい、その方向でお願い致します、私に手伝える事があれば
　可能な限り手伝わせて頂きますので、宜しくお願い致します

**Comment by lispcoc** [comment]
SpreadSheetのほうにja.jsonの中身をまとめました。URLを把握してる人ならだれでも編集できる状態です。
https://docs.google.com/spreadsheets/d/15VBRL7fyIylrfo-RAn1ZyITbDGHgo3fZUUjru6xkPZ8/edit?usp=sharing

編集した内容はリアルタイムでjsonに変換してこちらからダウンロード可能です。
https://script.google.com/macros/s/AKfycbwuMbnroUTF7Smrrfws2q0vwA79fkpBQZWCkCweK6JZwl_Ni4Sy/exec

ほかにもやったほうがいいこと（入力規則の設定とか）があると思いますが、だいたいこんな感じで問題ないかと思うので取り急ぎまでにご連絡します。

**Comment by YASUYASUYASUYASU** [comment]
返信遅くなり申し訳ありません
お手数お掛けしました、触りやすくていいですね、有難う御座います。
これに関しては近いうちに動画で宣伝させて頂きます
